import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './_layout/layout.module.css'
import { Footer, Header, Logo, Navbar } from './_layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shell/Host - MF1 - Layout',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.containerHero}>
          <div className={styles.sidebar}>
            <Logo />
            <Navbar />
          </div>

          <div className={styles.pageContainer}>
            <Header />
            <main className={styles.mainContainer}>
              Main content to be fetched on module federation and populate here
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
