import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './_layout/layout.module.css'
import { Logo, Navbar } from './_layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.containerHero}>
          <div className={styles.sidebar}>
            <Logo />
            <Navbar />
          </div>

          {/* <Header />
          <main>{children}</main>
          <Footer /> */}
        </div>
      </body>
      {/* <body className={inter.className}>{children}</body> */}
      {/* we inject our microfrontend component here */}
      {/* <main>{children}</main> */}
    </html>
  )
}
